import {createHmac,randomBytes,randomUUID} from 'node:crypto';import {db,tx,audit} from './database.mjs';
export const cookie='__Host-nuqte_session';
export const ready=()=>Boolean(process.env.DATABASE_URL&&process.env.APP_ORIGIN&&process.env.AUTH_PEPPER?.length>=32&&process.env.RESEND_API_KEY&&process.env.MAIL_FROM&&process.env.PERSONAL_DATA_LAUNCH_APPROVED==='true');
export const fail=(s,status=400)=>{throw Object.assign(Error(s),{status});};
export const launch=()=>{if(!ready())fail('Вход и приём заявок откроются после подключения базы данных и почты.',503);};
export const hash=v=>{if(!process.env.AUTH_PEPPER)fail('Не настроена авторизация',503);return createHmac('sha256',process.env.AUTH_PEPPER).update(v).digest('hex');};
export const origin=req=>{if(!process.env.APP_ORIGIN||req.headers.get('origin')!==new URL(process.env.APP_ORIGIN).origin)fail('Недопустимый источник запроса',403);};
export async function limit(key,max=10){const r=await db().query(`INSERT INTO limits VALUES($1,1,now()+interval '15 minutes') ON CONFLICT(key) DO UPDATE SET count=CASE WHEN limits.expires_at<now() THEN 1 ELSE limits.count+1 END,expires_at=CASE WHEN limits.expires_at<now() THEN now()+interval '15 minutes' ELSE limits.expires_at END RETURNING count`,[hash(key)]);if(r.rows[0].count>max)fail('Слишком много запросов. Попробуйте через 15 минут.',429);}
export async function user(req){launch();const v=req.cookies.get(cookie)?.value;if(!v)return null;const r=await db().query('SELECT a.id,a.email,a.name,a.role,a.organization FROM sessions s JOIN accounts a ON a.id=s.user_id WHERE s.hash=$1 AND s.expires_at>now() AND a.verified=true',[hash(v)]);return r.rows[0]||null;}
export async function link(email,name){await limit('email:'+email,4);const token=randomBytes(32).toString('hex'),digest=hash(token);await tx(async c=>{const r=await c.query('INSERT INTO accounts(id,email,name) VALUES($1,$2,$3) ON CONFLICT(email) DO UPDATE SET email=EXCLUDED.email RETURNING id',[randomUUID(),email,name||email.split('@')[0]]);await c.query("INSERT INTO login_tokens VALUES($1,$2,now()+interval '15 minutes')",[digest,r.rows[0].id]);});const url=new URL('/login',process.env.APP_ORIGIN);url.hash='token='+token;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':digest},body:JSON.stringify({from:process.env.MAIL_FROM,to:[email],subject:'Вход в NUQTE',text:`Для входа откройте ссылку: ${url}\nСсылка действует 15 минут и используется один раз. Если вы не запрашивали вход, проигнорируйте письмо.`}),signal:AbortSignal.timeout(10000)});if(!r.ok){await db().query('DELETE FROM login_tokens WHERE hash=$1',[digest]);fail('Письмо не удалось отправить. Попробуйте позже.',503);}}
export async function verify(token){const session=randomBytes(32).toString('hex');await tx(async c=>{const r=await c.query('DELETE FROM login_tokens WHERE hash=$1 AND expires_at>now() RETURNING user_id',[hash(token)]);if(!r.rowCount)fail('Ссылка использована или истекла. Запросите новую.');const id=r.rows[0].user_id;await c.query('UPDATE accounts SET verified=true WHERE id=$1',[id]);await c.query("INSERT INTO sessions VALUES($1,$2,now()+interval '7 days')",[hash(session),id]);await audit(c,{id},null,'session.created');});return session;}
