import {NextResponse} from 'next/server';import {randomUUID} from 'node:crypto';import {z} from 'zod';
import {db,tx,audit} from '@/lib/database.mjs';import {ready,launch,origin,user,limit,link,verify,cookie,hash,fail} from '@/lib/auth.mjs';import {canRead,staff,transition,validClasses,mime,statuses} from '@/lib/policy.mjs';
export const runtime='nodejs';export const dynamic='force-dynamic';
const uuid=z.string().uuid(),json=(data,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'no-store'}});
function error(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:'Проверьте поля и формат данных.'},400);if(e.status)return json({error:e.message},e.status);console.error('NUQTE request failed',e.code||e.name);return json({error:'Операция не выполнена. Попробуйте позже.'},500);}
async function getCase(c,u,id,lock=false){uuid.parse(id);const r=await c.query('SELECT * FROM cases WHERE id=$1'+(lock?' FOR UPDATE':''),[id]);if(!r.rowCount||!canRead(u,r.rows[0]))fail('Дело не найдено',404);return r.rows[0];}
export async function GET(req){try{
 const p=new URL(req.url).searchParams;if(p.get('resource')==='status')return json({ready:ready(),registry:false,payments:false,signing:false});
 const u=await user(req);if(!u)return json({user:null,cases:[],notifications:[],ledger:[]});
 if(p.has('document')){const r=await db().query('SELECT * FROM documents WHERE id=$1',[uuid.parse(p.get('document'))]);if(!r.rowCount)fail('Документ не найден',404);const d=r.rows[0];await getCase(db(),u,d.case_id);if(d.internal&&!staff(u.role))fail('Документ не найден',404);return new NextResponse(d.bytes,{headers:{'Content-Type':d.mime,'Content-Disposition':`attachment; filename="document"; filename*=UTF-8''${encodeURIComponent(d.name)}`,'Cache-Control':'private, no-store','Content-Security-Policy':"default-src 'none'; sandbox",'X-Content-Type-Options':'nosniff'}});}
 if(p.has('case')){const c=await getCase(db(),u,p.get('case')),s=staff(u.role);const [docs,msg,tasks,events]=await Promise.all([db().query('SELECT id,name,kind,internal,created_at FROM documents WHERE case_id=$1 AND ($2 OR internal=false) ORDER BY created_at',[c.id,s]),db().query('SELECT m.id,m.body,m.internal,m.created_at,a.name AS author FROM messages m JOIN accounts a ON a.id=m.author_id WHERE case_id=$1 AND ($2 OR internal=false) ORDER BY created_at',[c.id,s]),s?db().query('SELECT * FROM tasks WHERE case_id=$1 ORDER BY due_at NULLS LAST',[c.id]):Promise.resolve({rows:[]}),db().query("SELECT id,action,created_at,CASE WHEN $2 THEN details ELSE '{}'::jsonb END AS details FROM audit_events WHERE case_id=$1 AND ($2 OR action IN ('case.created','case.status')) ORDER BY id",[c.id,s])]);return json({case:c,documents:docs.rows,messages:msg.rows,tasks:tasks.rows,events:events.rows});}
 const params=u.role==='admin'?[]:[u.id],where=u.role==='admin'?'true':'(owner_id=$1 OR assignee_id=$1)';
 const [cases,notices,ledger,team]=await Promise.all([db().query(`SELECT id,number,name,service,status,owner_id,assignee_id,classes,version,updated_at FROM cases WHERE ${where} ORDER BY updated_at DESC LIMIT 500`,params),db().query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY id DESC LIMIT 100',[u.id]),db().query('SELECT id,kind,amount_tenge,tokens,created_at FROM ledger WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100',[u.id]),u.role==='admin'?db().query("SELECT id,name,role FROM accounts WHERE role IN ('admin','sales','legal') AND verified=true"):Promise.resolve({rows:[]})]);return json({user:u,cases:cases.rows,notifications:notices.rows,ledger:ledger.rows,team:team.rows});
 }catch(e){return error(e);}}
export async function POST(req){try{
 launch();origin(req);await limit('ip:'+(req.headers.get('x-vercel-forwarded-for')?.split(',')[0]||'unknown'),100);
 if(Number(req.headers.get('content-length')||0)>4000000)fail('Слишком большой запрос',413);
 if(req.headers.get('content-type')?.startsWith('multipart/form-data')){
 const u=await user(req);if(!u)fail('Войдите в кабинет',401);const f=await req.formData(),id=uuid.parse(f.get('caseId')),file=f.get('file'),kind=z.enum(['logo','contract','authority','receipt','filing','certificate','report','other']).parse(f.get('kind'));
 if(!(file instanceof File)||file.size===0||file.size>3145728)fail('Допустим PDF, PNG или JPEG до 3 МБ');const bytes=Buffer.from(await file.arrayBuffer()),type=mime(bytes);if(!type)fail('Неподдерживаемый формат файла');
 await tx(async c=>{await getCase(c,u,id,true);const n=await c.query('SELECT count(*)::int n FROM documents WHERE case_id=$1',[id]);if(n.rows[0].n>=40)fail('Лимит: 40 документов на дело');await c.query('INSERT INTO documents(id,case_id,author_id,name,mime,bytes,kind) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),id,u.id,file.name.replace(/[\x00-\x1f]/g,'').slice(0,150),type,bytes,kind]);await audit(c,u,id,'document.uploaded',{kind});});return json({ok:true});}
 const text=await req.text();if(Buffer.byteLength(text)>64000)fail('Слишком большой запрос',413);const b=JSON.parse(text);
 if(b.action==='login'){const v=z.object({email:z.string().trim().email().max(254).transform(x=>x.toLowerCase()),name:z.string().trim().max(100).optional()}).parse(b);await link(v.email,v.name);return json({ok:true,message:'Ссылка для входа отправлена на почту.'});}
 if(b.action==='verify'){const session=await verify(z.string().regex(/^[a-f0-9]{64}$/).parse(b.token));const r=json({ok:true});r.cookies.set(cookie,session,{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:604800});return r;}
 const u=await user(req);if(!u)fail('Войдите в кабинет',401);
 if(b.action==='logout'){const v=req.cookies.get(cookie)?.value;if(v)await db().query('DELETE FROM sessions WHERE hash=$1',[hash(v)]);const r=json({ok:true});r.cookies.set(cookie,'',{httpOnly:true,secure:true,sameSite:'lax',path:'/',maxAge:0});return r;}
 if(b.action==='create'){
 const v=z.object({id:uuid,service:z.enum(['scan','trademark','bridge']),name:z.string().trim().min(1).max(200),mark_type:z.enum(['text','image','combined']),activity:z.string().trim().min(3).max(3000),classes:z.array(z.number()).refine(validClasses),details:z.object({note:z.string().max(4000),certificate:z.string().max(100),seller:z.string().max(300),buyer:z.string().max(300),scope:z.enum(['full','partial'])}).strict(),consent:z.literal(true)}).parse(b);
 if(v.service==='bridge'&&(!v.details.certificate||!v.details.seller||!v.details.buyer))fail('Укажите свидетельство и обе стороны сделки');
 await tx(async c=>{const r=await c.query('INSERT INTO cases(id,owner_id,service,name,mark_type,activity,classes,details) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO NOTHING RETURNING id',[v.id,u.id,v.service,v.name,v.mark_type,v.activity,v.classes,JSON.stringify(v.details)]);if(!r.rowCount){const old=await getCase(c,u,v.id);if(old.owner_id!==u.id)fail('Дело не найдено',404);return;}await c.query('INSERT INTO tasks(id,case_id,title) VALUES($1,$2,$3)',[randomUUID(),v.id,'Назначить ответственного и срок первичного контакта']);await audit(c,u,v.id,'case.created',{consent_version:'2026-09-16'});await c.query('INSERT INTO notifications(user_id,case_id,body) VALUES($1,$2,$3)',[u.id,v.id,'Заявка сохранена в NUQTE. Подача в Казпатент ещё не выполнялась.']);});return json({ok:true,id:v.id});}
 if(b.action==='read_notifications'){await db().query('UPDATE notifications SET read_at=now() WHERE user_id=$1 AND read_at IS NULL',[u.id]);return json({ok:true});}
 if(b.action==='profile'){const v=z.object({name:z.string().trim().min(1).max(100),organization:z.string().trim().max(200)}).parse(b);await db().query('UPDATE accounts SET name=$1,organization=$2 WHERE id=$3',[v.name,v.organization,u.id]);return json({ok:true});}
 if(b.action==='partner_request'){await tx(async c=>{await audit(c,u,null,'partner.requested');await c.query("INSERT INTO notifications(user_id,body) SELECT id,$1 FROM accounts WHERE role='admin'",['Запрос партнёрства: '+u.email]);});return json({ok:true});}
 await tx(async c=>{const item=await getCase(c,u,uuid.parse(b.caseId),true);
 if(b.action==='message'){const v=z.object({body:z.string().trim().min(1).max(4000),internal:z.boolean().default(false)}).parse(b);if(v.internal&&!staff(u.role))fail('Нет прав',403);await c.query('INSERT INTO messages(id,case_id,author_id,body,internal) VALUES($1,$2,$3,$4,$5)',[randomUUID(),item.id,u.id,v.body,v.internal]);await audit(c,u,item.id,'message.created',{internal:v.internal});if(!v.internal&&u.id!==item.owner_id)await c.query('INSERT INTO notifications(user_id,case_id,body) VALUES($1,$2,$3)',[item.owner_id,item.id,'Новое сообщение по делу «'+item.name+'»']);return;}
 if(!staff(u.role))fail('Действие доступно сотруднику',403);
 if(b.action==='assign'){if(u.role!=='admin')fail('Назначает администратор',403);const id=uuid.parse(b.assignee);if(!(await c.query("SELECT 1 FROM accounts WHERE id=$1 AND verified=true AND role IN ('admin','sales','legal')",[id])).rowCount)fail('Сотрудник не найден');await c.query('UPDATE cases SET assignee_id=$1,version=version+1,updated_at=now() WHERE id=$2',[id,item.id]);await audit(c,u,item.id,'case.assigned',{assignee:id});return;}
 if(b.action==='task'){const v=z.object({title:z.string().trim().min(1).max(300),due:z.string().datetime({offset:true})}).parse(b);await c.query('INSERT INTO tasks(id,case_id,title,due_at) VALUES($1,$2,$3,$4)',[randomUUID(),item.id,v.title,v.due]);await audit(c,u,item.id,'task.created');return;}
 if(b.action==='task_done'){await c.query('UPDATE tasks SET done=$1 WHERE id=$2 AND case_id=$3',[z.boolean().parse(b.done),uuid.parse(b.taskId),item.id]);await audit(c,u,item.id,'task.updated');return;}
 if(b.action==='status'){const v=z.object({status:z.string(),version:z.number().int(),evidence:uuid.nullable(),note:z.string().trim().min(3).max(1000),filing_number:z.string().max(100).optional()}).parse(b);if(v.version!==item.version)fail('Дело изменилось. Обновите страницу.',409);let proof=null;if(v.evidence){proof=(await c.query('SELECT id,kind,internal FROM documents WHERE id=$1 AND case_id=$2',[v.evidence,item.id])).rows[0];if(!proof)fail('Документ не найден');}try{transition(u,item,v.status,proof,v.filing_number);}catch(e){fail(e.message,403);}await c.query('UPDATE cases SET status=$1,filing_number=COALESCE($2,filing_number),version=version+1,updated_at=now() WHERE id=$3',[v.status,v.filing_number||null,item.id]);await audit(c,u,item.id,'case.status',{from:item.status,to:v.status,evidence:v.evidence,note:v.note});await c.query('INSERT INTO notifications(user_id,case_id,body) VALUES($1,$2,$3)',[item.owner_id,item.id,'Стадия дела: '+statuses[v.status]]);return;}
 fail('Неизвестное действие');});return json({ok:true});
 }catch(e){return error(e);}}
